import 'package:trading_app/data_layer/mdoels/stock_model.dart';

List<StockModel> stockModelList = [
  StockModel(
    id: "1",
    name: "RELIANCE",
    exchange: "NSE",
    type: "EQ",
    price: 1374.10,
    change: -4.40,
    percentChange: -0.32,
  ),
  StockModel(
    id: "2",
    name: "HDFCBANK",
    exchange: "NSE",
    type: "EQ",
    price: 966.95,
    change: 0.95,
    percentChange: 0.10,
  ),
  StockModel(
    id: "3",
    name: "ASIANPAINT",
    exchange: "NSE",
    type: "EQ",
    price: 2537.40,
    change: 6.60,
    percentChange: 0.26,
  ),
  StockModel(
    id: "4",
    name: "NIFTY IT",
    exchange: "IDX",
    type: "",
    price: 35184.30,
    change: 873.86,
    percentChange: 2.55,
  ),
  StockModel(
    id: "5",
    name: "RELIANCE SEP 1880 CE",
    exchange: "NSE",
    type: "Monthly",
    price: 0.00,
    change: 0.00,
    percentChange: 0.00,
  ),
  StockModel(
    id: "6",
    name: "RELIANCE SEP 1370 PE",
    exchange: "NSE",
    type: "Monthly",
    price: 19.20,
    change: 1.00,
    percentChange: 5.49,
  ),
  StockModel(
    id: "7",
    name: "MRF",
    exchange: "NSE",
    type: "EQ",
    price: 147625.00,
    change: 550.00,
    percentChange: 0.37,
  ),
  StockModel(
    id: "8",
    name: "MRF",
    exchange: "BSE",
    type: "EQ",
    price: 147439.45,
    change: 463.80,
    percentChange: 0.32,
  )
];